/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20 } from "./Erc20";
export type { Kayswap_factory } from "./Kayswap_factory";
export type { Kayswap_pool } from "./Kayswap_pool";
