/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Kayswap_pool, Kayswap_poolInterface } from "../Kayswap_pool";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "token",
        type: "address",
      },
      {
        name: "amount",
        type: "uint256",
      },
    ],
    name: "estimatePos",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Kayswap_pool__factory {
  static readonly abi = _abi;
  static createInterface(): Kayswap_poolInterface {
    return new Interface(_abi) as Kayswap_poolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Kayswap_pool {
    return new Contract(address, _abi, runner) as unknown as Kayswap_pool;
  }
}
